quiz/accounts/urls.py
"""Account urls"""
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('privacy_policy/', views.show_privacy_policy, name='privacy_policy')
]

quiz/questions/urls.py
"""Questions urls"""
from django.urls import path

from . import views

app_name = 'questions'
urlpatterns = [
    path('create_question_title/<int:question_id>/<str:article_id>', views.create_question_title,
         name='create_question_title'),
    path('quizzes/<int:quiz_id>/create_question/', views.create_question, name='create_question'),
    path('create_question_stat/<int:question_id>/<str:article_id>',
         views.create_question_type_statistics,
         name='create_question_type_stat'),
    path('choose_question_type/<int:question_id>/<str:article_id>', views.choose_question_type,
         name='choose_question_type'),
    path('quizzes/<int:quiz_id>/questions', views.list_questions, name='questions'),
    path('quizzes/<int:quiz_id>/questions/<int:question_id>/delete',
         views.delete_question, name='delete_question'),
    path('quizzes/<int:quiz_id>/choose_best/<str:key_word>/', views.choose_best_article,
         name='choose_best_article'),
]

quiz/quiz/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=settings.STATIC_URL + 'favicon.ico')),
    path('', include('quizzes.urls')),
    path('', include('questions.urls', namespace='questions')),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

quiz/quizzes/urls.py
"""Quizzes urls"""
from django.urls import path

from . import views

app_name = 'quizzes'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create_quiz, name='create'),
    path('quizzes/', views.choose_quiz_to_play, name='quizzes'),
    path('quizzes/<int:quiz_id>/', views.open_quiz, name='quiz'),
    path('quizzes/<int:quiz_id>/delete', views.delete_quiz, name='delete_quiz'),
    path('quizzes/<int:quiz_id>/solve', views.solve_quiz, name='solve_quiz'),
    path('my_quizzes/', views.list_player_quizzes, name='my_quizzes'),
]

quiz/questions/models.py
"""Models defined for 'questions' app"""
from django.db import models

# Create your models here.

quiz/questions/forms.py
"""Forms"""
from bootstrap_datepicker_plus import MonthPickerInput
from django import forms

from quizzes.models import Question


class CreateQuestionForm(forms.ModelForm):
    """ form to create question"""
    answer = forms.CharField(max_length=200)

    class Meta:
        model = Question
        fields = ['answer']


class ChooseArticleForm(forms.Form):
    def __init__(self, articles, *args, **kwargs):
        super(ChooseArticleForm, self).__init__(*args, **kwargs)
        self.fields['Choose article'] = forms.ChoiceField(choices=articles,
                                                          widget=forms.RadioSelect)


class ChooseWordToHide(forms.Form):
    word = forms.CharField(max_length=200)


class EnterMonthAndYearForm(forms.Form):
    date = forms.DateField(input_formats=['%Y-%m'],
                           widget=MonthPickerInput(format='%Y-%m'))

quiz/questions/views.py
"""Views for the 'questions' app"""
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from quizzes.models import Question, Quiz

from .forms import ChooseWordToHide, CreateQuestionForm, ChooseArticleForm
from .forms import EnterMonthAndYearForm
from .mediawiki_utils import find_article, get_article_and_views, find_articles_list


def create_question(request: HttpRequest, quiz_id) -> HttpResponse:
    """Render the create question page"""
    if Quiz.objects.get(pk=quiz_id).author != request.user.id:  # type: ignore
        render(request, 'default_error.html')
    if request.method == 'POST':
        form = CreateQuestionForm(request.POST)
        if form.is_valid():
            key_word = form.save(commit=False)
            return redirect('questions:choose_best_article',
                            key_word=key_word.answer, quiz_id=quiz_id)
        return render(request, 'default_error.html')
    return render(request, 'question_generator_title.html',
                  context={'form': CreateQuestionForm(), 'generated': False})


def create_question_title(request: HttpRequest, article_id, question_id) -> HttpResponse:
    """Render the page to choose concrete article"""
    question = Question.objects.get(pk=question_id)  # type: ignore
    if question.quiz.author != request.user.id:  # type: ignore
        render(request, 'default_error.html')
    initialize_question(article_id, question)
    if request.method == 'POST':
        form = ChooseWordToHide(request.POST)
        if form.is_valid():
            replace_word(form, question)
            question.type = 'Title'
            question.article_id = article_id
            question.save()
            redirect('questions:create_question_title', article_id=article_id,
                     question_id=question_id)
        else:
            return render(request, 'default_error.html')
    context = {
        'article_id': article_id,
        'article': question.question_text,
        'title': question.answer,
        'chooser': ChooseWordToHide(),
        'quiz_id': question.quiz.id,
        'source_url': question.source_url
    }
    return render(request, 'create_question_title.html', context=context)


def replace_word(form, question):
    word = form.cleaned_data['word']
    question.question_text = question.question_text.replace(word, len(word) * " _")


def initialize_question(article_id, question):
    """helper function for filling the title-type question"""
    found_article = find_article(article_id)
    if question.question_text == '':
        question.question_text = 'What is the title of this article? "' \
                                 + found_article[0] + '"'
    if question.answer == '':
        question.answer = found_article[1]
    if question.source_url == '':
        question.source_url = found_article[2]


def create_question_type_statistics(request: HttpRequest, article_id, question_id) -> HttpResponse:
    """Render the create question page type statistics"""
    question = Question.objects.get(pk=question_id)  # type: ignore
    if question.quiz.author != request.user.id:  # type: ignore
        render(request, 'default_error.html')
    if request.method == 'POST':
        form = EnterMonthAndYearForm(request.POST)
        if form.is_valid():
            found_date = form.cleaned_data['date']
            found_article = get_article_and_views(article_id,
                                                  year=found_date.year, month=found_date.month)
            fill_stat_type_question(article_id, found_article, found_date, question)
            question.save()
            redirect('questions:create_question_type_stat',
                     article_id=article_id, question_id=question_id)
        else:
            print(form.errors)
            return render(request, 'default_error.html')
    context = {
        'article_id': article_id,
        'article': question.question_text,
        'title': find_article(article_id)[1],
        'form': EnterMonthAndYearForm(),
        'quiz': question.quiz,
    }
    return render(request, 'create_question_statistics.html', context=context)


def fill_stat_type_question(article_id, found_article, found_date, question):
    """Given an article, a date and some already gathered data, fill the details
    of a statistics-type question"""
    if question.source_url == '':
        question.source_url = found_article[2]
    question.question_text = \
        'How many times was the article "' \
        + found_article[0] + '" viewed in the month of ' \
        + str(found_date.year) + "-" + str(found_date.month) + "?"
    question.type = 'Statistic'
    question.article_id = article_id
    question.answer = found_article[1]


def choose_question_type(request: HttpRequest, article_id, question_id) -> HttpResponse:
    """Render the choose question type page"""
    question = Question.objects.get(pk=question_id)  # type: ignore
    if question.quiz.author != request.user.id:  # type: ignore
        render(request, 'default_error.html')
    found_article = find_article(article_id)
    return render(request, 'question_type_chooser.html',
                  context={'form': CreateQuestionForm(), 'generated': False,
                           'article': found_article[0],
                           'title': found_article[1], 'article_id': article_id,
                           'question_id': question_id})


def list_questions(request: HttpRequest, quiz_id) -> HttpResponse:
    """Render the page of list of all questions"""
    quiz = Quiz.objects.get(id=quiz_id)  # type: ignore
    questions = Question.objects.filter(quiz=quiz).order_by('id')  # type: ignore
    page = request.GET.get('page', 1)
    paginator = Paginator(questions, 10)
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)  # type: ignore
    context = {
        'questions': questions,  # type: ignore
        'quiz': quiz
    }
    return render(request, 'question_list.html', context)


def delete_question(request: HttpRequest, quiz_id, question_id) -> HttpResponse:
    """Delete the question specified by question_id."""
    author_id = Quiz.objects.get(id=quiz_id).author.id  # type: ignore
    if request.user.is_authenticated and (author_id == request.user.id):  # type: ignore
        Question.objects.filter(id=question_id).delete()  # type: ignore
        messages.success(request, 'Question deleted successfully.')  # type: ignore
        return redirect('questions:questions', quiz_id=quiz_id)
    return render(request, 'no_permission_error.html')


def choose_best_article(request: HttpRequest, quiz_id, key_word) -> HttpResponse:
    """Render the page to choose concrete article"""
    if Quiz.objects.get(pk=quiz_id).author != request.user.id:  # type: ignore
        render(request, 'default_error.html')
    data_list = find_articles_list(key_word)
    if request.method == 'POST':
        form = ChooseArticleForm(data_list, request.POST)
        if form.is_valid():
            pageid = form.cleaned_data['Choose article']
            question = Question.objects.create(  # type: ignore
                author_id=request.user.id, quiz_id=quiz_id, article_id=pageid)  # type: ignore
            return redirect('questions:choose_question_type',
                            article_id=pageid, question_id=question.id)
        return render(request, 'default_error.html')
    context = {
        'chooser': ChooseArticleForm(data_list)
    }
    return render(request, 'choose_article.html', context=context)

quiz/questions/templates/choose_article.html
{% extends 'base.html' %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'quizzes:index' %}">Home</a></li>
    {% if user.is_authenticated %}
    <li class="active"><a href="{% url 'quizzes:create' %}">Create</a></li>
    <li><a href="{% url 'quizzes:my_quizzes' %}">Your quizzes</a></li>
    {% endif %}
    <li><a href="{% url 'quizzes:quizzes' %}">Play</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <p class="navbar-text"><span class=" glyphicon glyphicon-user"></span> {{ user.get_username }} </p>
    <li><a href="{% url 'logout' %}"><span class=" glyphicon glyphicon-log-out"></span> Logout</a></li>
    {% else %}
    <li><a href="{% url 'accounts:signup' %}"><span class=" glyphicon glyphicon-user"></span> Sign Up</a></li>
    <li><a href="{% url 'login' %}"><span class=" glyphicon glyphicon-log-in"></span> Login</a></li>
    {% endif %}
</ul>
{% endblock navbar %}

{% block content %}

<div class="container-fluid">
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li
                {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="jumbotron">

        {% if user.is_authenticated %}

        <div class="jumbotron">
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}">
                {{ chooser.as_p }}

                <div class="container">
                    <input type="submit" value="Search"/>
                </div>

            </form>
        </div>

        {% else %}
        <div class="container">
            <div class="alert alert-danger">
                This page is available only for logged users.
            </div>
            <div class="text-center">
                <h1 class="glyphicon glyphicon-lock"></h1>
            </div>
        </div>
        {% endif %}

    </div>

</div>
{% endblock content %}

quiz/questions/templates/create_question_statistics.html
{% extends 'base.html' %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'quizzes:index' %}">Home</a></li>
    {% if user.is_authenticated %}
    <li class="active"><a href="{% url 'quizzes:create' %}">Create</a></li>
    <li><a href="{% url 'quizzes:my_quizzes' %}">Your quizzes</a></li>
    {% endif %}
    <li><a href="{% url 'quizzes:quizzes' %}">Play</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <li><a href="{% url 'logout' %}"><span class=" glyphicon glyphicon-log-out"></span> Logout</a></li>
    {% else %}
    <li><a href="{% url 'accounts:signup' %}"><span class=" glyphicon glyphicon-user"></span> Sign Up</a></li>
    <li><a href="{% url 'login' %}"><span class=" glyphicon glyphicon-log-in"></span> Login</a></li>
    {% endif %}
</ul>
{% endblock navbar %}

{% block content %}

<div class="container-fluid">
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li
                {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="jumbotron">

        {% if user.is_authenticated %}
        {% if article == '' %}
        <h2>
            This question will ask the user how many times article <i>{{ title }}</i> was viewed during a month you
            will now choose.
        </h2>
        {% else %}
        <h2>
            Currently this question is: <i>{{ article }}</i> .
        </h2>
        <h2>Change the month using the form below or accept the question by clicking one of the buttons.</h2>
        <div>
            <a href="{% url 'questions:questions' quiz_id=quiz.id %}">
                <button type="button" class="btn btn-default" id="user_quizzes_left">Save and move to
                    questions list
                </button>
            </a>
            <a href="{% url 'questions:create_question' quiz_id=quiz.id %}">
                <button type="button" class="btn btn-default" id="add_next_question_left">Save and add
                    next question
                </button>
            </a>
        </div>
        <br/><br/>
        Change the month:
        {% endif %}

        {{ form.media }}
        <form method="POST" style="max-width: 300px">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Confirm">
        </form>

        {% else %}
        <div class="container">
            <div class="alert alert-danger">
                This page is available only for logged users.
            </div>
            <div class="text-center">
                <h1 class="glyphicon glyphicon-lock"></h1>
            </div>
        </div>
        {% endif %}

    </div>
</div>
{% endblock content %}

quiz/questions/templates/create_question_title.html
{% extends 'base.html' %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'quizzes:index' %}">Home</a></li>
    {% if user.is_authenticated %}
    <li class="active"><a href="{% url 'quizzes:create' %}">Create</a></li>
    <li><a href="{% url 'quizzes:my_quizzes' %}">Your quizzes</a></li>
    {% endif %}
    <li><a href="{% url 'quizzes:quizzes' %}">Play</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <p class="navbar-text"><span class=" glyphicon glyphicon-user"></span> {{ user.get_username }}
    </p>
    <li><a href="{% url 'logout' %}"><span class=" glyphicon glyphicon-log-out"></span> Logout</a>
    </li>
    {% else %}
    <li><a href="{% url 'accounts:signup' %}"><span class=" glyphicon glyphicon-user"></span> Sign
        Up</a></li>
    <li><a href="{% url 'login' %}"><span class=" glyphicon glyphicon-log-in"></span> Login</a></li>
    {% endif %}
</ul>
{% endblock navbar %}

{% block content %}

<div class="container-fluid">
    {% if messages %}
    <ul style="color: #e4f4da;">
        {% for message in messages %}
        <li
                {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="jumbotron" id="jumbotrone_1">

        {% if user.is_authenticated %}

        <h2>
            Write down part of the question which needs to be hidden from the player in order to
            make it not painfully easy. For example, if the answer is "Pizza", you should probably
            erase all "pizza"s from the question. Just enter the word (or phrase) and click
            "Replace".
        </h2>

        <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {{ chooser.as_p }}

            <div class="container">
                <input type="submit" value="Replace"/>
            </div>

        </form>

        {% else %}
        <div class="container">
            <div class="alert alert-danger">
                This page is available only for logged users.
            </div>
            <div class="text-center">
                <h1 class="glyphicon glyphicon-lock"></h1>
            </div>
        </div>
        {% endif %}

    </div>

    <div class="jumbotron" id="jumbotrone_2">

        {% if user.is_authenticated %}

        <h3>Found article </h3>

        <p><strong> Title - future question answer:</strong> {{ title }} </p>
        <p><strong> Source url:</strong> {{ source_url }} </p>

        <div>
            <strong> Article - future question:</strong> {{ article }}
        </div>
        <br/>
        <br/>
        <div class="text-right">
            <a href="{% url 'questions:questions' quiz_id=quiz_id %}">
                <button type="button" class="btn btn-default" id="user_quizzes">Save and move to
                    questions list
                </button>
            </a>
            <a href="{% url 'questions:create_question' quiz_id=quiz_id %}">
                <button type="button" class="btn btn-default" id="add_next_question">Save and add
                    next question
                </button>
            </a>
        </div>

        {% endif %}

    </div>

</div>
{% endblock content %}

quiz/questions/templates/question_generator_title.html
{% extends 'base.html' %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'quizzes:index' %}">Home</a></li>
    <li class="active"><a href="{% url 'quizzes:create' %}">Create</a></li>
    <li><a href="{% url 'quizzes:my_quizzes' %}">Your quizzes</a></li>
    <li><a href="{% url 'quizzes:quizzes' %}">Play</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <p class="navbar-text"><span class=" glyphicon glyphicon-user"></span> {{ user.get_username }} </p>
    <li><a href="{% url 'logout' %}"><span class=" glyphicon glyphicon-log-out"></span> Logout</a></li>
    {% else %}
    <li><a href="{% url 'accounts:signup' %}"><span class=" glyphicon glyphicon-user"></span> Sign Up</a></li>
    <li><a href="{% url 'login' %}"><span class=" glyphicon glyphicon-log-in"></span> Login</a></li>
    {% endif %}
</ul>
{% endblock navbar %}

{% block content %}

<div class="container-fluid">
    {% if messages %}
   <ul style="color: #e4f4da;">
        {% for message in messages %}
        <li
                {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="jumbotron">

        {% if user.is_authenticated %}

        <h2>
            Your question will be generated based on a Wikipedia article - to choose which one, use this search window.
        </h2>

        <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {{ form.as_p }}

            <div class="container">
                <input type="submit" value="Search"/>
            </div>

        </form>

        {% else %}
        <div class="container">
            <div class="alert alert-danger">
                This page is available only for logged users.
            </div>
            <div class="text-center">
                <h1 class="glyphicon glyphicon-lock"></h1>
            </div>
        </div>
        {% endif %}

    </div>

</div>
{% endblock content %}

quiz/questions/templates/question_list.html
{% extends 'base.html' %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'quizzes:index' %}">Home</a></li>
    {% if user.is_authenticated %}
    <li><a href="{% url 'quizzes:create' %}">Create</a></li>
    <li class="active"><a href="{% url 'quizzes:my_quizzes' %}">Your quizzes</a></li>
    {% endif %}
    <li><a href="{% url 'quizzes:quizzes' %}">Play</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <p class="navbar-text"><span class=" glyphicon glyphicon-user"></span> {{ user.get_username }} </p>
    <li><a href="{% url 'logout' %}"><span class=" glyphicon glyphicon-log-out"></span> Logout</a></li>
    {% else %}
    <li><a href="{% url 'accounts:signup' %}"><span class=" glyphicon glyphicon-user"></span> Sign Up</a></li>
    <li><a href="{% url 'login' %}"><span class=" glyphicon glyphicon-log-in"></span> Login</a></li>
    {% endif %}
</ul>
{% endblock navbar %}

{% block content %}
<div class="container-fluid">

    {% if messages %}
    <ul style="color: #e4f4da;">
        {% for message in messages %}
        <li
                {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="jumbotron">
        <h2>Questions from quiz {{ quiz.name }}</h2>
        <p>Here you can edit or delete questions.</p>
        <table class="table">
            <thead>
            <tr>
                <th>Type</th>
                <th>Answer</th>
                <th>Source</th>
                <th>Published</th>
                <th>Text</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            </thead>
            </tr>
            <tr>
                {% for question in questions %}
            <tr>
                <td> {{ question.type }}</td>
                <td> {{ question.answer }}</td>
                <td> {{ question.source_url }}</td>
                <td> {{ question.published_date }}</td>
                <td> {{ question.question_text }}</td>
                <td>
                    {% if question.type == "Title"%}
                    <a href="{% url 'questions:create_question_title' article_id=question.article_id question_id=question.id %}"
                       class="btn btn-default" role="button" name="edit_button" id="title_button_{{ question.id }}">Edit</a>
                    {% else %}
                    <a href="{% url 'questions:create_question_type_stat' article_id=question.article_id question_id=question.id %}"
                       class="btn btn-default" role="button" name="edit_button" id="stat_button_{{ question.id }}">Edit</a>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'questions:delete_question' quiz_id=question.quiz.id question_id=question.id %}"
                       class="btn btn-danger" role="button" name="edit_button">Delete</a>
                </td>

            </tr>
            {% endfor %}
            </tr>
        </table>

        <ul class="pagination">
            {% if questions.has_previous %}
            <li><a href="?page={{ quizzes.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in questions.paginator.page_range %}
            {% if questions.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if questions.has_next %}
            <li><a href="?page={{ quizzes.next_page_number }}">&raquo;</a></li>
            {% else %}
            <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>

        <br/>
        <br/>
        <div class="text-right">
        <a href="{% url 'questions:questions' quiz_id=quiz.id %}">
            <button type="button" class="btn btn-default" id="user_quizzes">Questions list
            </button>
        </a>
        <a href="{% url 'questions:create_question' quiz_id=quiz.id %}">
            <button type="button" class="btn btn-default" id="add_next_question">Add next question
            </button>
        </a>
        </div>

    </div>
</div>
{% endblock content %}

quiz/questions/templates/question_type_chooser.html
{% extends 'base.html' %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'quizzes:index' %}">Home</a></li>
    {% if user.is_authenticated %}
    <li class="active"><a href="{% url 'quizzes:create' %}">Create</a></li>
    <li><a href="{% url 'quizzes:my_quizzes' %}">Your quizzes</a></li>
    {% endif %}
    <li><a href="{% url 'quizzes:quizzes' %}">Play</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <p class="navbar-text"><span class=" glyphicon glyphicon-user"></span> {{ user.get_username }} </p>
    <li><a href="{% url 'logout' %}"><span class=" glyphicon glyphicon-log-out"></span> Logout</a></li>
    {% else %}
    <li><a href="{% url 'accounts:signup' %}"><span class=" glyphicon glyphicon-user"></span> Sign Up</a></li>
    <li><a href="{% url 'login' %}"><span class=" glyphicon glyphicon-log-in"></span> Login</a></li>
    {% endif %}
</ul>
{% endblock navbar %}

{% block content %}
<div class="container-fluid">

    {% if messages %}
    <ul style="color: #e4f4da;">
        {% for message in messages %}
        <li
                {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="jumbotron">
        <div class="page-header">
            <h2>
                Choose question type
            </h2>
        </div>

        <div class="row">
            <div class="col-sm-6">

                <a href="{% url 'questions:create_question_title' article_id=article_id question_id=question_id %}">
                    <button type="button" class="btn btn-primary btn-block">Basic</button>
                </a>
                <div class="jumbotron"> This kind of question consists of the beginning of your chosen Wikipedia article
                    with selected words removed. The title of the article will be the answer. In the next step, you will
                    choose which words need to be removed to make the question not too obvious.
                </div>
            </div>
            <div class="col-sm-6">
                <a href="{% url 'questions:create_question_type_stat' article_id=article_id question_id=question_id %}">
                    <button type="button" class="btn btn-primary btn-block">Statistics</button>
                </a>
                <div class="jumbotron"> This kind of question asks about how many times a particular page was viewed
                    during a chosen month.
                </div>
            </div>
        </div>
    </div>

    <div class="jumbotron">

        {% if user.is_authenticated %}

        <h3>Used article</h3>

        <p> Title: {{ title }} </p>

        <div class="jumbotron">
            {{ article }}
        </div>

        {% endif %}

    </div>
</div>
{% endblock content %}

quiz/questions/templates/show_generated_question.html
{% extends 'base.html' %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'quizzes:index' %}">Home</a></li>
    {% if user.is_authenticated %}
    <li class="active"><a href="{% url 'quizzes:create' %}">Create</a></li>
    <li><a href="{% url 'quizzes:my_quizzes' %}">Your quizzes</a></li>
    {% endif %}
    <li><a href="{% url 'quizzes:quizzes' %}">Play</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <p class="navbar-text"><span class=" glyphicon glyphicon-user"></span> {{ user.get_username }} </p>
    <li><a href="{% url 'logout' %}"><span class=" glyphicon glyphicon-log-out"></span> Logout</a></li>
    {% else %}
    <li><a href="{% url 'accounts:signup' %}"><span class=" glyphicon glyphicon-user"></span> Sign Up</a></li>
    <li><a href="{% url 'login' %}"><span class=" glyphicon glyphicon-log-in"></span> Login</a></li>
    {% endif %}
</ul>
{% endblock navbar %}

{% block content %}

<div class="container-fluid">
    {% if messages %}
    <ul style="color: #e4f4da;">
        {% for message in messages %}
        <li
                {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="jumbotron">

        {% if user.is_authenticated %}

        <h3>Used article </h3>

        <p> Title: {{ title }} </p>

        <div class="jumbotron">
            {{ article }}
        </div>

        {% endif %}

    </div>

</div>
{% endblock content %}