quiz/accounts/urls.py
"""Account urls"""
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('privacy_policy/', views.show_privacy_policy, name='privacy_policy')
]

quiz/questions/urls.py
"""Questions urls"""
from django.urls import path

from . import views

app_name = 'questions'
urlpatterns = [
    path('create_question_title/<int:question_id>/<str:article_id>', views.create_question_title,
         name='create_question_title'),
    path('quizzes/<int:quiz_id>/create_question/', views.create_question, name='create_question'),
    path('create_question_stat/<int:question_id>/<str:article_id>',
         views.create_question_type_statistics,
         name='create_question_type_stat'),
    path('choose_question_type/<int:question_id>/<str:article_id>', views.choose_question_type,
         name='choose_question_type'),
    path('quizzes/<int:quiz_id>/questions', views.list_questions, name='questions'),
    path('quizzes/<int:quiz_id>/questions/<int:question_id>/delete',
         views.delete_question, name='delete_question'),
    path('quizzes/<int:quiz_id>/choose_best/<str:key_word>/', views.choose_best_article,
         name='choose_best_article'),
]

quiz/quiz/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=settings.STATIC_URL + 'favicon.ico')),
    path('', include('quizzes.urls')),
    path('', include('questions.urls', namespace='questions')),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

quiz/quizzes/urls.py
"""Quizzes urls"""
from django.urls import path

from . import views

app_name = 'quizzes'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create_quiz, name='create'),
    path('quizzes/', views.choose_quiz_to_play, name='quizzes'),
    path('quizzes/<int:quiz_id>/', views.open_quiz, name='quiz'),
    path('quizzes/<int:quiz_id>/delete', views.delete_quiz, name='delete_quiz'),
    path('quizzes/<int:quiz_id>/solve', views.solve_quiz, name='solve_quiz'),
    path('my_quizzes/', views.list_player_quizzes, name='my_quizzes'),
]

quiz/quizzes/models.py
"""Quizzes models"""
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class Player(AbstractUser):
    """User of app"""
    username: models.CharField = models.CharField(max_length=50, unique=True)
    email: models.EmailField = models.EmailField()
    date_joined: models.DateTimeField = models.DateTimeField("date joined", default=timezone.now)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username


class Quiz(models.Model):
    """Model of quiz"""
    name: models.CharField = models.CharField(max_length=100, null=False, default='')
    category: models.CharField = models.CharField(max_length=100, null=False, default='')
    topic: models.CharField = models.CharField(max_length=100, null=False, default='')
    description: models.CharField = models.CharField(max_length=100)
    author: models.ForeignKey = models.ForeignKey(
        Player, on_delete=models.CASCADE, related_name='quiz_author')

    def __str__(self):
        return self.topic


class Question(models.Model):
    """Model of question"""
    question_text: models.CharField = models.CharField(max_length=4196, null=False, default='')
    source_url: models.URLField = models.URLField()
    answer: models.CharField = models.CharField(max_length=1000, null=False, default='')
    author: models.ForeignKey = models.ForeignKey(
        Player, on_delete=models.CASCADE, related_name='question_author')
    published_date: models.DateTimeField = models.DateTimeField(
        "date published", default=timezone.now)
    quiz: models.ForeignKey = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    article_id: models.IntegerField = models.IntegerField(null=False)
    TYPES = (
        ('Title', 'Title'),
        ('Stats', 'Statistics')
    )

    type: models.CharField = models.CharField(
        max_length=2,
        choices=TYPES,
        default='Title',
    )

    def __str__(self):
        return self.question_text

quiz/quizzes/forms.py
"""Forms"""
from django import forms
from django.forms.widgets import TextInput

from .models import Question, Quiz, Player

categories = (
    ('ACTORS', 'ACTORS'), ('AFRICA', 'AFRICA'), ('AMERICA', 'AMERICA'), ('ANATOMY', 'ANATOMY'),
    ('ANIMALS', 'ANIMALS'),
    ('ART', 'ART'), ('ASIA', 'ASIA'), ('AUSTRALIA', 'AUSTRALIA'), ('AUTOMOTIVE', 'AUTOMOTIVE'),
    ('AVIATION', 'AVIATION'),
    ('BASEBALL', 'BASEBALL'), ('BASKETBALL', 'BASKETBALL'), ('BIOLOGY', 'BIOLOGY'),
    ('BIRD', 'BIRD'),
    ('CHEMISTRY', 'CHEMISTRY'), ('CHINA', 'CHINA'), ('CHRISTMAS', 'CHRISTMAS'),
    ('COMPUTER', 'COMPUTER'),
    ('COUNTRIES', 'COUNTRIES'),
    ('DISNEY', 'DISNEY'), ('DOG', 'DOG'),
    ('EARTH', 'EARTH'), ('EASY', 'EASY'), ('ENGLAND', 'ENGLAND'), ('EUROPE', 'EUROPE'),
    ('FAMOUS PEOPLE', 'FAMOUS PEOPLE'), ('FOOD AND DRINK', 'FOOD AND DRINK'),
    ('FOOTBALL', 'FOOTBALL'),
    ('FRANCE', 'FRANCE'),
    ('GAMES', 'GAMES'), ('GENERAL KNOWLEDGE', 'GENERAL KNOWLEDGE'), ('GEOGRAPHY', 'GEOGRAPHY'),
    ('GERMANY', 'GERMANY'),
    ('GOLF', 'GOLF'),
    ('HARRY POTTER', 'HARRY POTTER'), ('HISTORY', 'HISTORY'), ('HOCKEY', 'HOCKEY'),
    ('ITALY', 'ITALY'),
    ('JAPAN', 'JAPAN'),
    ('KIDS', 'KIDS'),
    ('LANGUAGE', 'LANGUAGE'), ('LITERATURE', 'LITERATURE'),
    ('MILITARY', 'MILITARY'), ('MONEY', 'MONEY'), ('MOON', 'MOON'), ('MOVIE', 'MOVIE'),
    ('MUSIC', 'MUSIC'),
    ('NEWS', 'NEWS'),
    ('OCEAN', 'OCEAN'), ('OLYMPICS', 'OLYMPICS'),
    ('PHYSICS', 'PHYSICS'), ('PLACES', 'PLACES'), ('PLANET', 'PLANET'), ('POLAND', 'POLAND'),
    ('POLITICAL', 'POLITICAL'), ('PORTUGAL', 'PORTUGAL'), ('PSYCHOLOGY', 'PSYCHOLOGY'),
    ('QUOTES', 'QUOTES'),
    ('RELIGIONS', 'RELIGIONS'),
    ('SAINTS', 'SAINTS'), ('SCIENCE', 'SCIENCE'), ('SPACE', 'SPACE'), ('SPAIN', 'SPAIN'),
    ('SPORTS', 'SPORTS'),
    ('STRANGER THINGS', 'STRANGER THINGS'), ('SUPER BOWL', 'SUPER BOWL'),
    ('TRAVEL', 'TRAVEL'), ('TV', 'TV'),
    ('UK', 'UK'), ('USA', 'USA'),
    ('VIDEO GAMES', 'VIDEO GAMES'),
    ('WORLD', 'WORLD'),
    ('OTHER', 'OTHER')
)

general_categories = categories + (('ALL', 'ALL_CATEGORIES'),)


class CreateQuizForm(forms.ModelForm):
    """ form to create quiz"""
    name = forms.CharField(max_length=50,
                           help_text='This name will represent your quiz on the site.')
    category = forms.TypedChoiceField(choices=categories)
    topic = forms.CharField(max_length=50, help_text='Choose the exact topic within the category.')
    description = forms.CharField(max_length=50, required=False,
                                  help_text='Describe your quiz in a few words. Not required.')

    class Meta:
        model = Quiz
        fields = ['name', 'category', 'topic', 'description']


class CreateQuestionForm(forms.ModelForm):
    """ form to create question"""
    answer = forms.CharField(max_length=200)

    class Meta:
        model = Question
        fields = ['answer']


class ChooseArticleForm(forms.Form):
    def __init__(self, articles, *args, **kwargs):
        super(ChooseArticleForm, self).__init__(*args, **kwargs)
        self.fields['Choose article'] = forms.ChoiceField(choices=articles,
                                                          widget=forms.RadioSelect)


class ChooseWordToHide(forms.Form):
    word = forms.CharField(max_length=200)


class EnterAnswerGuess(forms.Form):
    def __init__(self, *args, **kwargs):
        super(EnterAnswerGuess, self).__init__(*args, **kwargs)
        self.fields['Answer'] = forms.CharField(max_length=200)


class FilterQuizForm(forms.ModelForm):
    """ form to filter quiz"""
    name = forms.CharField(max_length=50, required=False)
    author = forms.ModelChoiceField(queryset=Player.objects.all(),  # type: ignore
                                    to_field_name='id',
                                    required=False)
    category = forms.TypedChoiceField(choices=general_categories, required=False, initial="ALL")
    topic = forms.CharField(max_length=50, required=False)

    def __init__(self, *args, **kwargs):
        super(FilterQuizForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'id': field
            })

    class Meta:
        model = Quiz
        fields = ['name', 'author', 'category', 'topic']

quiz/quizzes/views.py
"""Quizzes views"""
from difflib import SequenceMatcher

from django import forms
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect

from .forms import CreateQuizForm, EnterAnswerGuess, FilterQuizForm
from .models import Player, Quiz, Question


def index(_request: HttpRequest) -> HttpResponse:
    """Render the main page"""
    context: dict = {}
    return render(_request, 'index.html', context)


def create_quiz(request: HttpRequest) -> HttpResponse:
    """Render the create quiz page"""
    if request.method == 'POST':
        form = CreateQuizForm(request.POST)
        if form.is_valid():
            added_quiz = form.save(commit=False)
            if request.user.is_authenticated:  # type: ignore
                added_quiz.author = Player.objects.get(pk=request.user.id)  # type: ignore
                added_quiz.save()
                messages.success(request, 'Quiz successfully added!')  # type: ignore
                return redirect('quizzes:quiz', quiz_id=added_quiz.id)
            return redirect('quizzes:index')
        return HttpResponse("WHAT ARE YOU DOING?")
    return render(request, 'quiz_generator.html', context={'form': CreateQuizForm()})


def list_player_quizzes(request: HttpRequest) -> HttpResponse:
    """Render the players own created quizzes page"""
    context = {'form': FilterQuizForm(), 'own': True}
    quizzes = Quiz.objects.all().order_by('id')  # type: ignore
    if request.method == 'POST':
        form = FilterQuizForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['author']:
                quizzes = quizzes.filter(author=form.cleaned_data['author'])
            if form.cleaned_data['category'] and form.cleaned_data['category'] != "ALL":
                quizzes = quizzes.filter(category=form.cleaned_data['category'])
            if form.cleaned_data['topic']:
                quizzes = quizzes.filter(topic=form.cleaned_data['topic'])
    if request.user.is_authenticated:  # type: ignore
        user = Player.objects.get(id=request.user.id)  # type: ignore
        quizzes = quizzes.filter(author=user)  # type: ignore
    page = request.GET.get('page', 1)
    paginator = Paginator(quizzes, 10)
    try:
        quizzes = paginator.page(page)
    except PageNotAnInteger:
        quizzes = paginator.page(1)
    except EmptyPage:
        quizzes = paginator.page(paginator.num_pages)  # type: ignore
    context['quizzes'] = quizzes
    return render(request, 'user_quizzes.html', context)


def choose_quiz_to_play(request):
    """Render the all quizzes created by all users page exclude this logged in"""
    context = {'form': FilterQuizForm()}
    quizzes = Quiz.objects.all().order_by('id')  # type: ignore
    if request.method == 'POST':
        form = FilterQuizForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['name']:
                quizzes = quizzes.filter(name__icontains=form.cleaned_data['name'])
            if form.cleaned_data['author']:
                quizzes = quizzes.filter(author=form.cleaned_data['author'])
            if form.cleaned_data['category'] and form.cleaned_data['category'] != "ALL":
                quizzes = quizzes.filter(category=form.cleaned_data['category'])
            if form.cleaned_data['topic']:
                quizzes = quizzes.filter(topic__icontains=form.cleaned_data['topic'])
    if request.user.is_authenticated:
        quizzes = quizzes.exclude(author=request.user)  # type: ignore
    else:
        quizzes = quizzes
    page = request.GET.get('page', 1)
    paginator = Paginator(quizzes, 10)
    try:
        quizzes = paginator.page(page)
    except PageNotAnInteger:
        quizzes = paginator.page(1)
    except EmptyPage:
        quizzes = paginator.page(paginator.num_pages)
    context['quizzes'] = quizzes
    return render(request, 'all_quizzes.html', context=context)


def open_quiz(request, quiz_id):
    """Render the single quiz page"""
    quiz = Quiz.objects.get(pk=quiz_id)  # type: ignore
    if request.user.is_authenticated and (quiz.author.id == request.user.id):
        return render(request, 'quiz_edit_page.html', context={'quiz': quiz})
    return render(request, 'quiz_start_page.html',
                  context={'quiz': quiz, 'any_questions': bool(Question.objects.filter(quiz=quiz))})


def solve_quiz(request: HttpRequest, quiz_id) -> HttpResponse:
    """Render the page for solving the quiz"""
    enter_title_guess_form_set = forms.formset_factory(EnterAnswerGuess, extra=0)  # type: ignore
    questions = Question.objects.filter(quiz=quiz_id)  # type: ignore
    if request.method == "POST":
        score = 0
        questions_number = 0
        formset = enter_title_guess_form_set(request.POST,
                                             initial=[{'question': question}
                                                      for question in questions])
        if formset.is_valid():
            for form in formset:
                questions_number += 1
                cleaned_data = form.cleaned_data
                score = add_score_for_question(cleaned_data, form, score)
            return render(request, 'quiz_results.html',
                          context={'result': '%.2f' % (100 * score / questions_number)})
    formset = enter_title_guess_form_set(initial=[{'question': question} for question in questions])
    return render(request, 'solve_quiz.html', context={'formset': formset})


def delete_quiz(request: HttpRequest, quiz_id) -> HttpResponse:
    """Delete the quiz specified by quiz_id."""
    author_id = Quiz.objects.get(id=quiz_id).author.id  # type: ignore
    if request.user.is_authenticated and (author_id == request.user.id):  # type: ignore
        Quiz.objects.filter(id=quiz_id).delete()  # type: ignore
        messages.success(request, 'Quiz deleted successfully.')  # type: ignore
        return redirect('quizzes:my_quizzes')
    return render(request, 'no_permission_error.html')


def add_score_for_question(cleaned_data, form, score):
    """increase score by a value in [0,1] depending on how 'close'
    given answer is to the original"""
    correct_answer = form.initial.get('question').answer.lower()
    user_answer = cleaned_data.get('Answer').lower()
    if form.initial.get('question').type == 'Title':
        score += SequenceMatcher(None, correct_answer, user_answer).ratio()
    else:
        try:
            correct_answer = float(correct_answer)
            user_answer = float(user_answer)
            if user_answer > 2 * correct_answer or user_answer < 0.5 * correct_answer:
                return score
            score += 1 - (abs(correct_answer - user_answer) / correct_answer)
        except (ValueError, ZeroDivisionError) as _:
            pass  # can't be correct => zero score
    return score

quiz/quizzes/templates/create_question_title.html
{% extends 'base.html' %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'quizzes:index' %}">Home</a></li>
    {% if user.is_authenticated %}
    <li class="active"><a href="{% url 'quizzes:create' %}">Create</a></li>
    <li><a href="{% url 'quizzes:my_quizzes' %}">Your quizzes</a></li>
    {% endif %}
    <li><a href="{% url 'quizzes:quizzes' %}">Play</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <p class="navbar-text"><span class=" glyphicon glyphicon-user"></span> {{ user.get_username }}
    </p>
    <li><a href="{% url 'logout' %}"><span class=" glyphicon glyphicon-log-out"></span> Logout</a>
    </li>
    {% else %}
    <li><a href="{% url 'accounts:signup' %}"><span class=" glyphicon glyphicon-user"></span> Sign
        Up</a></li>
    <li><a href="{% url 'login' %}"><span class=" glyphicon glyphicon-log-in"></span> Login</a></li>
    {% endif %}
</ul>
{% endblock navbar %}

{% block content %}

<div class="container-fluid">
    {% if messages %}
    <ul style="color: #e4f4da;">
        {% for message in messages %}
        <li
                {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="jumbotron" id="jumbotrone_1">

        {% if user.is_authenticated %}

        <h2>
            Write down part of the question which needs to be hidden from the player in order to
            make it not painfully easy. For example, if the answer is "Pizza", you should probably
            erase all "pizza"s from the question. Just enter the word (or phrase) and click
            "Replace".
        </h2>

        <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {{ chooser.as_p }}

            <div class="container">
                <input type="submit" value="Replace"/>
            </div>

        </form>

        {% else %}
        <div class="container">
            <div class="alert alert-danger">
                This page is available only for logged users.
            </div>
            <div class="text-center">
                <h1 class="glyphicon glyphicon-lock"></h1>
            </div>
        </div>
        {% endif %}

    </div>

    <div class="jumbotron" id="jumbotrone_2">

        {% if user.is_authenticated %}

        <h3>Found article </h3>

        <p> <strong> Title - future question answer:</strong> {{ title }} </p>
        <p> <strong> Source url:</strong> {{ source_url }} </p>

        <div>
            <strong> Article - future question:</strong> {{ article }}
        </div>
        <br/>
        <br/>
        <div class="text-right">
        <a href="{% url 'quizzes:questions' quiz_id=quiz_id %}">
            <button type="button" class="btn btn-default" id="user_quizzes">Questions list
            </button>
        </a>
        <a href="{% url 'quizzes:create_question' quiz_id=quiz_id %}">
            <button type="button" class="btn btn-default" id="add_next_question">Add next question
            </button>
        </a>
        </div>

        {% endif %}

    </div>

</div>
{% endblock content %}

quiz/quizzes/templates/default_error.html
{% extends 'base.html' %}

{% block navbar %}
<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <p class="navbar-text"><span class=" glyphicon glyphicon-user"></span> {{ user.get_username }} </p>
    {% endif %}
</ul>
{% endblock navbar %}

{% block content %}
<div class="container-fluid">
    <div class="jumbotron">
       <div class="basic">
            Unfortunately, this operation has resulted in an error. You may need to try again. If the problem persist even after trying again from the home page, please contact the site administrators with as much information about the problem as you can gather.
        </div>
    </div>
</div>
{% endblock content %}

quiz/quizzes/templates/index.html
{% extends 'base.html' %}

{% block style %}

.btn-default {
background-color: #e9f9df;
font-size : 30px;
width: 50%;
height: 50px;
}

.lets-play {
font-weight: bold;
}

{% endblock style %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li class="active"><a href="{% url 'quizzes:index' %}">Home</a></li>
    {% if user.is_authenticated %}
    <li><a href="{% url 'quizzes:create' %}">Create</a></li>
    <li><a href="{% url 'quizzes:my_quizzes' %}">Your quizzes</a></li>
    {% endif %}
    <li><a href="{% url 'quizzes:quizzes' %}">Play</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <p class="navbar-text"><span class=" glyphicon glyphicon-user"></span> {{ user.get_username }}
    </p>
    <li><a href="{% url 'logout' %}"><span class=" glyphicon glyphicon-log-out"></span> Logout</a>
    </li>
    {% else %}
    <li><a href="{% url 'accounts:signup' %}"><span class=" glyphicon glyphicon-user"></span> Sign
        Up</a></li>
    <li><a href="{% url 'login' %}"><span class=" glyphicon glyphicon-log-in"></span> Login</a></li>
    {% endif %}
</ul>
{% endblock navbar %}

{% block content %}
<div class="container-fluid">
    <div class="jumbotron">
        <div class="page-header">
            <h1>
                Quizzes
            </h1>

        </div>
    </div>
    <div class="well well-lg">
        <p class="lead">If you like having your knowledge tested and helping others to do so, you're
            in a right
            place! Here you can create and solve various quizzes on topics limited only by the
            imagination of our
            users.</p>
        <p class="lead">There's a catch, though: creating a quiz doesn't mean just typing in a
            question and an answer.
            Our quizzes are based on the knowledge treasure trove that is Wikipedia. How does it
            work? <a
                    href="{% url 'accounts:signup' %}">Create an account</a> if you haven't already,
            <a
                    href="{% url 'login' %}">log in</a> and try to
            {% if user.is_authenticated %}
            <a href="{% url 'quizzes:create' %}">create a quiz</a>
            {% else %}
            create a quiz
            {% endif %}
            yourself - or, if you'd rather stay a stranger for a while, <a
                    href="{% url 'quizzes:quizzes' %}">solve one
                of the quizzes</a> that are already available.</p>
        <p class="lead">Whatever you decide to do - have fun!</p>
        <div style="text-align: center;">
            <a href="{% url 'quizzes:quizzes' %}">
                <button type="button" class="btn btn-default lets-play">Let's play!
                </button>
            </a>
        </div>

    </div>
</div>

<footer>
    <div class="navbar navbar-inverse navbar-static-bottom" role="navigation">
        <div class="navbar-text pull-left">
            <a href="{% url 'accounts:privacy_policy' %}" class="btn btn-link">Privacy Policy</a>
        </div>
    </div>
</footer>
{% endblock content %}

quiz/quizzes/templates/question_generator.html
{% extends 'base.html' %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'quizzes:index' %}">Home</a></li>
    <li class="active"><a href="{% url 'quizzes:create' %}">Create</a></li>
    <li><a href="{% url 'quizzes:my_quizzes' %}">Your quizzes</a></li>
    <li><a href="{% url 'quizzes:quizzes' %}">Play</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <li><a href="{% url 'logout' %}"><span class=" glyphicon glyphicon-log-out"></span> Logout</a></li>
    {% else %}
    <li><a href="{% url 'accounts:signup' %}"><span class=" glyphicon glyphicon-user"></span> Sign Up</a></li>
    <li><a href="{% url 'login' %}"><span class=" glyphicon glyphicon-log-in"></span> Login</a></li>
    {% endif %}
</ul>
{% endblock navbar %}

{% block content %}

<div class="container-fluid">
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li
                {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="jumbotron">

        {% if user.is_authenticated %}

        <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {{ form.as_p }}

            <div class="container">
                <input type="submit" value="Search"/>
            </div>

        </form>

        {% else %}
        <div class="container">
            <div class="alert alert-danger">
                This page is available only for logged users.
            </div>
            <div class="text-center">
                <h1 class="glyphicon glyphicon-lock"></h1>
            </div>
        </div>
        {% endif %}

    </div>

    {% if generated %}
    <div class="jumbotron">

        <p> Generated question: </p>
        <p> {{ question }} </p>
    </div>
    {% endif %}

</div>
{% endblock content %}

quiz/quizzes/templates/question_type_chooser.html
{% extends 'base.html' %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'quizzes:index' %}">Home</a></li>
    {% if user.is_authenticated %}
    <li class="active"><a href="{% url 'quizzes:create' %}">Create</a></li>
    <li><a href="{% url 'quizzes:my_quizzes' %}">Your quizzes</a></li>
    {% endif %}
    <li><a href="{% url 'quizzes:quizzes' %}">Play</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <p class="navbar-text"><span class=" glyphicon glyphicon-user"></span> {{ user.get_username }} </p>
    <li><a href="{% url 'logout' %}"><span class=" glyphicon glyphicon-log-out"></span> Logout</a></li>
    {% else %}
    <li><a href="{% url 'accounts:signup' %}"><span class=" glyphicon glyphicon-user"></span> Sign Up</a></li>
    <li><a href="{% url 'login' %}"><span class=" glyphicon glyphicon-log-in"></span> Login</a></li>
    {% endif %}
</ul>
{% endblock navbar %}

{% block content %}
<div class="container-fluid">

    {% if messages %}
    <ul style="color: #e4f4da;">
        {% for message in messages %}
        <li
                {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="jumbotron">
        <div class="page-header">
            <h2>
                Choose question type
            </h2>
        </div>

        <div class="row">
            <div class="col-sm-6">

                <a href="{% url 'quizzes:create_question_title' article_id=article_id question_id=question_id%}">
                    <button type="button" class="btn btn-primary btn-block">Basic</button>
                </a>
                <div class="jumbotron"> This kind of question consists of the beginning of your chosen Wikipedia article
                    with selected words removed. The title of the article will be the answer. In the next step, you will
                    choose which words need to be removed to make the question not too obvious.
                </div>
            </div>
            <div class="col-sm-6">
                <a href="{% url 'quizzes:create_question_type_stat' %}">
                    <button type="button" class="btn btn-primary btn-block">Statistics</button>
                </a>
                <div class="jumbotron"> This kind of question asks about the statistics collected by Wikipedia.
                    Currently creating this kind of questions is impossible.
                </div>
            </div>
        </div>
    </div>

    <div class="jumbotron">

        {% if user.is_authenticated %}

        <h3>Used article</h3>

        <p> Title: {{ title }} </p>

        <div class="jumbotron">
            {{ article }}
        </div>

        {% endif %}

    </div>
</div>
{% endblock content %}